# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger: none

pool:
  vmImage: 'ubuntu-latest'

jobs:
- job: build_ios
  pool:
    vmImage: "macOS-latest"
  steps:
    - script: brew install fastlane
      displayName: Install fastlane

    - script: |
        git checkout master

    - script: fastlane init
      workingDirectory: $(Build.DefaultWorkingDirectory)/ios
      displayName: fastlane init (iOS)

    - script: |
        git add .
        git commit -m "Changes"
        git push
    


